openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Brvey test
    url: https://virtserver.swaggerhub.com/odinds/qrveySwagger/1.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Qrbey test Inventory API
  contact:
    email: odinds@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: qrbey 
    description: Secured Admin-only calls
  - name: odinds
    description: Operations available to regular developers
paths:
  /user:
    post:
      tags:
        - create user
      summary: adds an user item
      operationId: addUser
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserItem'
        description: Inventory item to add  
  /user/resumeTask:
    get:
      tags:
        - users
      summary: searches inventory
      operationId: searchInventory
      description: GEt user with the resume of tasks
      parameters:
        - in: query
          name: idUser
          description: pass mandatory parameter
          required: false
          schema:
            type: string
      responses:
        '200':
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserTaskItem'
        '400':
          description: bad input parameter
  /project:
    post:
      tags:
        - create project
      summary: adds an user item
      operationId: addPoject
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectItem'
        description: Inventory item to add
  /tasks:
    post:
      tags:
        - create task
      summary: adds an user item
      operationId: addTask
      description: Adds an item to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskItem'
        description: Inventory item to add            
components:
  schemas:
    UserItem:
      type: object
      required:
        - fullname
        - email
      properties:
        fullname:
          type: string
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        email:
          type: string
          example: oddd@gmail.com
    TaskItem:
      type: object
      required:
        - idUser
      properties:
        idUser:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
    ProjectItem:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: Project_1
    UserTaskItem:
      type: object
      required:
        - id
        - fullName
        - email
        - tasks
        - createdAt
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        fullName:
          type: string
          example: Carlos Prueba Perez
        email:
          type: string
          example: Carlos Pruba PErez          
        createdAt:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/TaskItem'